name: Generate Daily Puzzle

on:
  schedule:
    # 00:00 Europe/Zagreb (22:00 UTC in summer)
    - cron: "0 22 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate puzzles (no API)
        run: node tools/generate-daily.js

      - name: Validate puzzles
        run: node tools/validate.mjs

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add puzzles/*.json
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore: add/validate daily puzzles"
            git push
          fi
