name: Generate Daily Puzzle

on:
  schedule:
    # Run at 22:00 UTC daily = 00:00 Europe/Zagreb (CEST summer)
    - cron: "0 22 * * *"
  workflow_dispatch: {} # allow manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install openai@latest

      - name: Generate puzzle for today
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          node scripts/generate-puzzle.mjs

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add puzzles/*.json
          git diff --cached --quiet || git commit -m "chore: add puzzle for $(date -u +%F)"
          git push
